# Generated by Django 4.2.10 on 2025-04-10 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint_id', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField()),
                ('trust_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser', models.CharField(max_length=128)),
                ('os', models.CharField(max_length=128)),
                ('headless', models.BooleanField()),
                ('entropy_score', models.FloatField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='api.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(max_length=64)),
                ('challenge_data', models.JSONField()),
                ('response_data', models.JSONField()),
                ('passed', models.BooleanField()),
                ('time_taken_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_logs', to='api.usersession')),
            ],
        ),
    ]
